### ISSUE TITLE
MFE Theming

### ISSUE THREAD

**Issue by antoviaque** [openedx/wg-community#42]
Work to support MFE theming and unify theming in Open edX.

See:
* https://discuss.openedx.org/t/open-edx-branding-and-theming-improvements/4747
* https://gitlab.com/opencraft/dev/branding-and-theming/-/merge_requests/1
* OEROADMAP-13 was the original proposal by @bradenmacdonald.

**Comment by arbrandes** [comment]
This is being addressed via several frontend initiatives, such as [this OEP](https://github.com/openedx/open-edx-proposals/pull/410) and [the design tokens initiative](https://github.com/openedx/paragon/issues/1546).  We can close this.
